### ISSUE TITLE
Can't load Kernel binary: Invalid kernel binary format version.

### ISSUE THREAD

**Issue by fehernyul** [f3ath/cider#14]
Hi, 
I installed cider with "pub global activate cider", after I run: "cider bump build" and it crashed with error message: 
**"Can't load Kernel binary: Invalid kernel binary format version."**.

What is the solution?

![image](https://user-images.githubusercontent.com/25593792/95192476-8c1a6a00-07d2-11eb-9309-7edc83ea120c.png)

When I use the "pubver" package, I got this:

![image](https://user-images.githubusercontent.com/25593792/95192848-182c9180-07d3-11eb-8c16-60e42171b80f.png)

I have flutter 1.22.0 (stable), Dart 2.10.0 (stable), and Windows 8.1 x64

**Comment by f3ath** [comment]
Seems to be a broken dart installation. Not related to the project.
