### ISSUE TITLE
Managing prereleases (like with npm version)

### ISSUE THREAD

**Issue by nilsreichardt** [f3ath/cider#17]
## Problem
I want manage my prereleases (`beta` & `alpha`). Simply said I would like to do the same as in this question:

> There is a very handy npm version command. Besides arguments like major, minor and patch it accepts arguments like prerelease, prepatch, etc.
> It says in the docs that the commands work in accordance with the semver.inc function.
> 
> These pre commands I have a question about.
> 
> Say I'm currently at version v1.0.0.
> If I run npm version prerelease it will bump version to v1.0.1-0.
> 
> Is it possible to provide an extra agrument for a prerelease identifier according to https://github.com/npm/node-semver#prerelease-identifiers?
> 
> I wish something like npm version prerelease alpha would bump version to v1.0.1-alpha.0 but that doesn't work.

Source: https://stackoverflow.com/q/44567010/8358501

The Answer to this question:
> $ npm version prerelease --preid=alpha
> v0.1.1-alpha.0
> $ npm version prerelease --preid=alpha
> v0.1.1-alpha.1
> $ npm version prerelease --preid=alpha
> v0.1.1-alpha.2

Source: https://stackoverflow.com/a/51888437/8358501

## Goal
My goal is to do the same thing but with `cider` for Dart. I miss this feature in `cider`. Like:
```
$ cider version
v0.1.1
$ cider bump prerelease --preid=alpha
v0.1.1-alpha.0
$ cider bump prerelease --preid=alpha
v0.1.1-alpha.1
$ cider bump prerelease --preid=alpha
v0.1.1-alpha.2
$ cider bump prerelease --preid=beta
v0.1.1-beta.0
$ cider bump prerelease --preid=beta
v0.1.1-beta.1
```

**Comment by f3ath** [comment]
At the first glance this seems doable. Will take a look.

**Comment by f3ath** [comment]
Hi @nilsreichardt I've been trying to sketch a set of commands and options for Cider to accommodate for your use case, but the example does not seem fully semver compliant. The semantics of version bump imply that the next version is always higher than the previous one. In the same time, semver specifies that

> Pre-release versions have a lower precedence than the associated normal version.

In your example we're going from `0.1.1` to `0.1.1-alpha.0` which is backwards in terms of version precedence. 

So far, it seems that:
- `bump prerelease` should fail if the current version is not a pre-release one
- `--preid=<value>` should be used first of all when bumping major, minor or patch, and only in some cases with prerelease

I also tend to use `pre` to reference pre-releases.

Please consider the following examples and let me know what you think.
```
$ cider version
v0.1.1
$ cider bump patch --pre=alpha
v0.1.2-alpha
$ cider bump pre
v0.1.2-alpha.0
$ cider bump pre
v0.1.2-alpha.1

```
```
$ cider version
v0.1.1
$ cider bump pre
ERROR: invalid version sequence
```
```
$ cider version
v0.1.1-rc.0
$ cider bump pre --pre=alpha
ERROR: invalid version sequence
```

@rubenvereecken you might be also interested in this.

**Comment by nilsreichardt** [comment]
Hi @f3ath Great to see some progress!

> In your example we're going from 0.1.1 to 0.1.1-alpha.0 which is backwards in terms of version precedence.

Yes, this makes more sense. My bad!

> I also tend to use pre to reference pre-releases.

Good idea! 👍

> `bump prerelease` should fail if the current version is not a pre-release one

This would be one option. `npm version` behavior is different:
```
$ npm version
1.0.0
$ npm version prerelease
1.0.1-0
$ npm version prerelease --preid=alpha
1.0.1-alpha.0
$ npm version prerelease --preid=beta
1.0.1-beta.0
$ npm version patch
1.0.1
```
I would prefer the behavior from `npm version`. But if you want we can also choose a different behavior.

If we go this way:
```
$ cider version
v0.1.1-rc.0
$ cider bump pre --pre=alpha
ERROR: invalid version sequence
```
Then I think we should have an option to remove the prerelease tag, so it's easier to change the prerelease or going from prerelease to release

**Comment by f3ath** [comment]
v0.1 will have this feature. I have published a [dev build](https://pub.dev/packages/cider/versions/0.1.0-dev.0) (very early and lacking some tests). Feel free to try it out if you're brave enough :)

Version bumping: https://github.com/f3ath/cider/blob/v0.1/README.md#bumping-the-project-version
Tests: https://github.com/f3ath/cider/blob/v0.1/test/functional_test.dart#L100

**Comment by nilsreichardt** [comment]
Thanks for the implementation, @f3ath! Since https://github.com/f3ath/cider/pull/21 is merged, we can close this ticket, right?
