### ISSUE TITLE
Please update to nullsafty to support flutter ^2.0.0

### ISSUE THREAD

**Issue by guenth39** [f3ath/cider#18]

**Comment by f3ath** [comment]
Acknowleged

**Comment by f3ath** [comment]
v0.1 will be null-safe. I have published a [dev build](https://pub.dev/packages/cider/versions/0.1.0-dev.0) (very early and lacking some tests). Feel free to try it out if you're brave enough :)

**Comment by f3ath** [comment]
Closing since v0.1 is out.
