### ISSUE TITLE
Lower required Dart sdk version

### ISSUE THREAD

**Issue by mrRedSun** [f3ath/cider#30]
The current Dart SDK version is 2.14.4.

Because [REDACTED] depends on cider >=0.1.1 which requires SDK version >=2.15.1 <3.0.0, version solving failed.
pub get failed (1; Because [REDACTED] depends on cider >=0.1.1 which requires SDK version >=2.15.1 <3.0.0, version solving failed.)

I don't see a reason why version couldn't be lower

**Comment by ropiDK** [comment]
I think it required minimum sdk version  2.15.1 but your SDK is 2.14.4 you need to update your SDK... Cmiiw

**Comment by f3ath** [comment]
I believe this is outdated. Feel free to reopen.
