### ISSUE TITLE
Support for listing versions

### ISSUE THREAD

**Issue by clragon** [f3ath/cider#48]
Cider supports printing out the changelog for a version with `cider describe [<version>]`

This is incredibly useful for CI.
However, I have a script in which I would like to generate a changelog file for each version.
To do so, I would need to know which versions are available.

Would it be possible to add a command that prints all versions in the changelog?

**Comment by f3ath** [comment]
Not sure I completely understand the idea. Can you maybe give a short example?

**Comment by clragon** [comment]
(it would also be really really nice if `describe` allowed getting only the body, without the title and the link at the end. perhaps as an optional flag. but maybe thats better for another issue)

**Comment by f3ath** [comment]
Hey @clragon wanna try the `list` command? https://pub.dev/packages/cider/versions/0.2.0-aplha.1

**Comment by clragon** [comment]
that works brilliantly!

**Comment by f3ath** [comment]
Implemented in `0.2`.
