### ISSUE TITLE
Error: No value found at /cider

### ISSUE THREAD

**Issue by MohamedFBoussaid** [f3ath/cider#57]
While trying to extract my pubspec.yaml version using : `cider version`

I am getting the following error : `No value found at /cider`

I using the latest version `^0.2.0`, and running the command on my project root folder. 

I have also tried : `cider --project-root=PATH_PROJCT_ROOT version`, but I am getting same error. 

Last time I have used this command and it was working as expected, was a week ago. 

Any idea what I am missing ?

**Comment by f3ath** [comment]
This looks like a nasty bug which I introduced in 0.2.0. Thanks for reporting, I'm working on it.

**Comment by f3ath** [comment]
Please try 0.2.1.

**Comment by MohamedFBoussaid** [comment]
Thank you @f3ath for the quick fix. 
it is working now with the `0.2.1`
I will close the bug.
