### ISSUE TITLE
Difference between [Unreleased] and Unreleased

### ISSUE THREAD

**Issue by digitaljoni** [f3ath/cider#6]
I see that there are 2 "Unreleased" sections:

```
## Unreleased

## \[Unreleased\]
```

What is the difference between the two?

**Comment by f3ath** [comment]
Most likely you had the `[Unreleased]` line without the actual link. Square brackets In markdown are for links. The library follows the keepachangelog format as closely as possible. So it kept whatever you had in your file and added an empty "Unreleased" section as the format suggests. That's my guess.

**Comment by digitaljoni** [comment]
Ok cool. Not sure what happened. I just use cider to update the file. Maybe something else is changing it somehow. 

Anyway, thanks!
