### ISSUE TITLE
Documentation doesn't match `log` subcommands

### ISSUE THREAD

**Issue by guidezpl** [f3ath/cider#73]
The subcommands use present tense (e.g 'added' and 'removed') while the documentation uses past tense (as before)

```
Available subcommands:
  add         Add a new feature to the changelog
  change      Add a new change to the changelog
  deprecate   Add a new deprecation to the changelog
  fix         Add a new bug fix to the changelog
  remove      Add a new removal to the changelog
  security    Add a new security fix to the changelog
```

**Comment by f3ath** [comment]
Version 0.2.7 should allow any prefix for the log command, e.g.
- `cider log f "A bug fixed"`
- `cider log fix "A bug fixed"`
- `cider log fixed "A bug fixed"`
 should work equally well. Please LMK if that works for you.

**Comment by guidezpl** [comment]
thanks!
