### ISSUE TITLE
Allow setting version explicitly

### ISSUE THREAD

**Issue by danilofuchs** [f3ath/cider#9]
I have some pipelines to analyze commit messages and generate a new automatic version number. I would like to be able to use
`cider bump 0.1.0` or `cider version 0.1.0` or something similar, instead of relying on bumping the version by change type

**Comment by PlugFox** [comment]
@danilofuchs add feature in PR
#11

**Comment by f3ath** [comment]
Implemented in [0.0.5](https://pub.dev/packages/cider/versions/0.0.5)
